### ISSUE TITLE
Błąd przy odczycie

### ISSUE THREAD

**Issue by pawelosin** [andrzejf1994/homebridge-airly-v2#1]
Przy próbie odczytu pojawia się błąd i homebridge się wyłącza. Jakieś sugestie.

19-5-12 08:09:55] Homebridge is running on port 42533.
[2019-5-12 08:10:01] TypeError: Cannot read property 'toString' of undefined
    at AirAccessory.updateData (/usr/local/lib/node_modules/homebridge-airly-v2/index.js:96:66)
    at Request._callback (/usr/local/lib/node_modules/homebridge-airly-v2/index.js:65:32)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-airly-v2/node_modules/request/request.js:185:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-airly-v2/node_modules/request/request.js:1161:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-airly-v2/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:314:30)
[2019-5-12 08:10:01] Got SIGTERM, shutting down Homebridge...

**Comment by MBarti** [comment]
u mnie tak samo j/w

**Comment by bartasdiver** [comment]
#2 Please review

**Comment by pawelosin** [comment]
I had updated the index.js file but still something is wrong.
[2019-5-28 23:45:15] TypeError: Cannot read property 'value' of undefined
at AirAccessory.updateData (/usr/local/lib/node_modules/homebridge-airly-v2/index.js:92:89)
at Request._callback (/usr/local/lib/node_modules/homebridge-airly-v2/index.js:65:32)
at Request.self.callback (/usr/local/lib/node_modules/homebridge-airly-v2/node_modules/request/request.js:185:22)
at emitTwo (events.js:125:13)
at Request.emit (events.js:213:7)
at Request. (/usr/local/lib/node_modules/homebridge-airly-v2/node_modules/request/request.js:1161:10)
at emitOne (events.js:115:13)
at Request.emit (events.js:210:7)
at IncomingMessage. (/usr/local/lib/node_modules/homebridge-airly-v2/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:314:30)
[2019-5-28 23:45:15] Got SIGTERM, shutting down Homebridge...
pi@raspberrypi2:~ $

**Comment by bartasdiver** [comment]
Looks like you don't get correct response from API, please check apikey

**Comment by MBarti** [comment]
Same here, I double-checked the API key and long&lat. Same error:
May 29 12:31:52 raspberrypi homebridge[15855]:         this.log.info("[%s] Airly air quality is: %s.", type, aqi.toString());
May 29 12:31:52 raspberrypi homebridge[15855]:                                                                   ^
May 29 12:31:52 raspberrypi homebridge[15855]: TypeError: Cannot read property 'toString' of undefined
May 29 12:31:52 raspberrypi homebridge[15855]:     at AirAccessory.updateData (/usr/lib/node_modules/homebridge-airly-v2/index.js:96:67)
May 29 12:31:52 raspberrypi homebridge[15855]:     at Request._callback (/usr/lib/node_modules/homebridge-airly-v2/index.js:65:32)
May 29 12:31:52 raspberrypi homebridge[15855]:     at Request.self.callback (/usr/lib/node_modules/homebridge-airly-v2/node_modules/request/request.js:185:22)
May 29 12:31:52 raspberrypi homebridge[15855]:     at Request.emit (events.js:197:13)
May 29 12:31:52 raspberrypi homebridge[15855]:     at Request.<anonymous> (/usr/lib/node_modules/homebridge-airly-v2/node_modules/request/request.js:1161:10)
May 29 12:31:52 raspberrypi homebridge[15855]:     at Request.emit (events.js:197:13)
May 29 12:31:52 raspberrypi homebridge[15855]:     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-airly-v2/node_modules/request/request.js:1083:12)
May 29 12:31:52 raspberrypi homebridge[15855]:     at Object.onceWrapper (events.js:285:13)
May 29 12:31:52 raspberrypi homebridge[15855]:     at IncomingMessage.emit (events.js:202:15)
May 29 12:31:52 raspberrypi homebridge[15855]:     at endReadableNT (_stream_readable.js:1129:12)
May 29 12:31:52 raspberrypi homebridge[15855]:     at processTicksAndRejections (internal/process/next_tick.js:76:17)

**Comment by pawelosin** [comment]
When I had typed my coordinates in index.js file the plugin starts working and I can see air quality.

**Comment by bartasdiver** [comment]
@pawelosin wygląda na to, że nie masz niezaktualizowany index.js, na npm jest cały czas poprzednia wersja i @andrzejf1994 musi podbić. Pobierz z repo i podmień w: `/usr/lib/node_modules/homebridge-airly-v2/`

**Comment by MBarti** [comment]
@bartasdiver Dziękuję, oczywiście masz rację. 

All fixed now!

**Comment by dajmirycyny** [comment]
@bartasdiver dzięki, mi też pomogło!

**Comment by spxcly** [comment]
@MBarti @dajmirycyny @bartasdiver 
 Hello, I would like to ask, how does the altitude operation work like this? If not please give an example, thank you!


    // Latitude and longitude
    this.lat = config['latitude'];
    this.lng = config['longitude'];


    if (!this.lat) throw new Error("Airly - you must provide a config value for 'latitude'.");
    if (!this.lng) throw new Error("Airly - you must provide a config value for 'longitude'.");

**Comment by Nubzor** [comment]
I did a fork of this repository and have released a proper and working version to npm repository. The new repository is available here: https://github.com/Nubzor/homebridge-airly-v2.
