### ISSUE TITLE
Homebridge problem

### ISSUE THREAD

**Issue by pl-samurai** [andrzejf1994/homebridge-airly-v2#3]
Error: The requested accessory 'Air' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by andrzejf1994** [comment]
@Nubzor did better job than I in [https://github.com/Nubzor/homebridge-airly-v2](his repo)

**Comment by andrzejf1994** [comment]
@Nubzor did better job than I did in [his repository](https://github.com/Nubzor/homebridge-airly-v2)
